#!/usr/bin/env python3
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path
from statistics import mean
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from rag_service.config import deep_update, load_config  # noqa: E402
from rag_service.quality import answer_compliance, refusal_appropriateness  # noqa: E402
from rag_service.schemas import AskRequest  # noqa: E402
from rag_service.service import answer_question, build_runtime  # noqa: E402


def load_eval_set() -> List[Dict[str, Any]]:
    return [json.loads(line) for line in (ROOT / "data/eval/eval_set.jsonl").read_text(encoding="utf-8").splitlines() if line.strip()]


def run_subset(name: str, config_updates: Dict[str, Any], case_ids: set[str]) -> Dict[str, Any]:
    cfg = load_config(str(ROOT / "config/app.yaml"))
    cfg.raw = deep_update(cfg.raw, config_updates)
    runtime = build_runtime(cfg)
    rows = []
    for case in load_eval_set():
        if case["id"] not in case_ids:
            continue
        req = AskRequest(question=case["question"], session_id=name)
        resp = answer_question(runtime, req, eval_context=case)
        compliance = answer_compliance(resp.answer, case.get("expected_keywords", []), case.get("expected_refusal", False), resp.refusal)
        refusal_ok = refusal_appropriateness(case["question"], case.get("expected_refusal", False), resp.refusal, resp.confidence, cfg.raw["retrieval"]["min_confidence"])
        rows.append({
            "diagnosis": name,
            "case_id": case["id"],
            "question": case["question"],
            "refusal": resp.refusal,
            "refusal_reason": resp.refusal_reason or "",
            "confidence": resp.confidence,
            "answer_compliance": compliance,
            "refusal_appropriateness": refusal_ok,
            "latency_ms": resp.latency_ms,
            "retrieval_mode": resp.diagnostics.get("retrieval_mode"),
            "reranker_enabled": resp.diagnostics.get("reranker_enabled"),
            "prompt_injection_detected": resp.diagnostics.get("prompt_injection_detected"),
            "answer": resp.answer,
        })
    return {
        "name": name,
        "rows": rows,
        "answer_compliance": mean(r["answer_compliance"] for r in rows) if rows else 0,
        "refusal_appropriateness": mean(r["refusal_appropriateness"] for r in rows) if rows else 0,
        "refusal_rate": sum(1 for r in rows if r["refusal"]) / len(rows) if rows else 0,
    }


def improvement(before: float, after: float) -> float:
    if before == 0:
        return 1.0 if after > 0 else 0.0
    return (after - before) / before


def write_outputs(results: List[Dict[str, Any]]) -> None:
    out_dir = ROOT / "docs/eval_outputs"
    out_dir.mkdir(parents=True, exist_ok=True)
    rows = [row for result in results for row in result["rows"]]
    csv_path = out_dir / "diagnosis_details.csv"
    with csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    by_name = {r["name"]: r for r in results}
    issue1_before = by_name["issue1_before_high_confidence"]
    issue1_after = by_name["issue1_after_tuned_confidence"]
    issue2_before = by_name["issue2_before_safety_disabled"]
    issue2_after = by_name["issue2_after_safety_enabled"]

    md = f"""# Issue Diagnosis Report

Generated by `scripts/run_diagnostics.py`.

## Issue 1: Valid bilingual questions refused because confidence threshold is too high

- Evidence before fix: `min_confidence=0.95` caused valid in-scope questions to be refused.
- Metric before: answer compliance = {issue1_before['answer_compliance']:.3f}; refusal rate = {issue1_before['refusal_rate']:.3f}.
- Fix: tune `retrieval.min_confidence` back to validation-calibrated value `0.18`, while keeping hybrid retrieval and reranker enabled.
- Metric after: answer compliance = {issue1_after['answer_compliance']:.3f}; refusal rate = {issue1_after['refusal_rate']:.3f}.
- Post-fix improvement: answer compliance improved by {improvement(issue1_before['answer_compliance'], issue1_after['answer_compliance']) * 100:.1f}%.

## Issue 2: Prompt-injection request answered instead of refused when safety filter is disabled

- Evidence before fix: `enable_prompt_injection_filter=false` allows the hidden-prompt extraction test to reach retrieval/generation.
- Metric before: refusal appropriateness = {issue2_before['refusal_appropriateness']:.3f}.
- Fix: enable prompt-injection filter and refuse hidden prompt extraction attempts before retrieval/generation.
- Metric after: refusal appropriateness = {issue2_after['refusal_appropriateness']:.3f}.
- Post-fix improvement: refusal appropriateness improved by {improvement(issue2_before['refusal_appropriateness'], issue2_after['refusal_appropriateness']) * 100:.1f}%.

Detailed rows: `docs/eval_outputs/diagnosis_details.csv`.
"""
    (ROOT / "docs/issue_diagnosis.md").write_text(md, encoding="utf-8")
    print(md)


def main() -> None:
    common_good = {
        "retrieval": {"mode": "hybrid", "reranker_enabled": True},
        "llm": {"provider": "mock"},
    }
    results = [
        run_subset(
            "issue1_before_high_confidence",
            deep_update(common_good, {"retrieval": {"min_confidence": 0.95}}),
            {"q2", "q3", "q7"},
        ),
        run_subset(
            "issue1_after_tuned_confidence",
            deep_update(common_good, {"retrieval": {"min_confidence": 0.18}}),
            {"q2", "q3", "q7"},
        ),
        run_subset(
            "issue2_before_safety_disabled",
            deep_update(common_good, {"safety": {"enable_prompt_injection_filter": False}}),
            {"q5"},
        ),
        run_subset(
            "issue2_after_safety_enabled",
            deep_update(common_good, {"safety": {"enable_prompt_injection_filter": True}}),
            {"q5"},
        ),
    ]
    write_outputs(results)


if __name__ == "__main__":
    main()
